In [ ]:
import numpy as np
import numpy.linalg as nla
import scipy.linalg as sla
import copy
import pandas as pd

**1. Степенной метод нахождения собственных значений (метод итераций)**

In [ ]:
A = [[6, -2, 2], 
     [-2, 5, 0], 
     [2, 0, 7]]

Находим наибольший собственное значение и соответствующий собственный вектор.

К этому вектору стремится $$v_k = \frac{A^k v_0}{\left\| A^k v_0\right\|}$$ для $v_0$ общего положения.

In [ ]:
n = len(A)
v = np.ones(3) # берём вектор (1, 1, 1) как вектор общего положения

for i in range(3):
  for j in range(21): # делаем 20 итераций
    u = A@v
    v = u/nla.norm(u)

  l_max = nla.norm(A@v)/nla.norm(v) # наибольшее собственное значение
  print("Собственное значение: {:}".format(l_max))
  print("Собственный вектор: {:} ".format(v))

  A -= (l_max/(v@v))* np.outer(v,v) # вычитаем матрицу ранга 1 с наиб. собственным значением и соотв. собственным вектором

  print("\n Новая матрица")
  print(A)
  print("\n")


Собственное значение: 8.999999899513641
Собственный вектор: [ 0.66659982 -0.33319967  0.66680031] 

 Новая матрица
[[ 2.00080211e+00 -1.00245134e-03 -2.00040069e+00]
 [-1.00245134e-03  4.00080183e+00  1.99959876e+00]
 [-2.00040069e+00  1.99959876e+00  2.99839616e+00]]


Собственное значение: 6.000000180875442
Собственный вектор: [ 0.3335338  -0.66676688 -0.66646615] 

 Новая матрица
[[ 1.3333333   1.33333335 -0.6666667 ]
 [ 1.33333335  1.33333332 -0.66666665]
 [-0.6666667  -0.66666665  0.3333333 ]]


Собственное значение: 2.9999999999999996
Собственный вектор: [ 0.66666667  0.66666667 -0.33333333] 

 Новая матрица
[[-3.57177345e-08  1.78508102e-08 -3.57338491e-08]
 [ 1.78508102e-08 -8.92137786e-09  1.78588639e-08]
 [-3.57338491e-08  1.78588639e-08 -3.57499705e-08]]




**2. QR-алгоритм**

In [ ]:
A = [[6, -2, 2], 
     [-2, 5, 0], 
     [2, 0, 7]]


for i in range(16):
  if i% 5 == 0:
    print('\n На шаге {:}'.format(i))
    print(A) 

  Q, R = nla.qr(A)
  A = R@Q
    


 На шаге 0
[[6, -2, 2], [-2, 5, 0], [2, 0, 7]]

 На шаге 5
[[ 8.98694904  0.19474511 -0.03688349]
 [ 0.19474511  6.00097376 -0.18957806]
 [-0.03688349 -0.18957806  3.0120772 ]]

 На шаге 10
[[8.99977447e+00 2.60100913e-02 1.52409770e-04]
 [2.60100913e-02 6.00021408e+00 5.86089440e-03]
 [1.52409770e-04 5.86089440e-03 3.00001145e+00]]

 На шаге 15
[[ 8.99999609e+00  3.42548289e-03 -6.27225062e-07]
 [ 3.42548289e-03  6.00000390e+00 -1.83106304e-04]
 [-6.27225064e-07 -1.83106304e-04  3.00000001e+00]]


Посмотрим - работает ли QR алгоритм для несимметричных матриц

In [ ]:
A = [[6, -2, 4], 
     [-5, 5, 0], 
     [2, 0, 7]]


for i in range(106):
  if i% 5 == 0:
    print('\n На шаге {:}'.format(i))
    print(A) 

  Q, R = nla.qr(A)
  A = R@Q


 На шаге 0
[[6, -2, 4], [-5, 5, 0], [2, 0, 7]]

 На шаге 5
[[ 1.02461815e+01  2.56428907e+00  9.68539500e-01]
 [ 9.54517117e-02  6.15809208e+00 -2.45446859e+00]
 [-1.00294949e-03 -1.21685389e-02  1.59572639e+00]]

 На шаге 10
[[ 1.03010498e+01  2.47326410e+00 -9.23526342e-01]
 [ 7.17988876e-03  6.10954954e+00  2.46284291e+00]
 [ 8.87876880e-08  1.37208725e-05  1.58940066e+00]]

 На шаге 15
[[ 1.03049738e+01  2.46660641e+00  9.19626131e-01]
 [ 5.25018968e-04  6.10563301e+00 -2.46429106e+00]
 [-7.75561296e-12 -1.63324798e-08  1.58939321e+00]]

 На шаге 20
[[ 1.03052596e+01  2.46611972e+00 -9.19340547e-01]
 [ 3.83246758e-05  6.10534716e+00  2.46439760e+00]
 [ 6.76866475e-16  1.95219507e-11  1.58939320e+00]]

 На шаге 25
[[ 1.03052805e+01  2.46608419e+00  9.19319701e-01]
 [ 2.79722360e-06  6.10532629e+00 -2.46440538e+00]
 [-5.90693892e-20 -2.33413407e-14  1.58939320e+00]]

 На шаге 30
[[ 1.03052820e+01  2.46608160e+00 -9.19318179e-01]
 [ 2.04160574e-07  6.10532477e+00  2.46440594e+00]
 [ 

Видно, что QR алгоритм приводит почти к верхнетреугольной матрице, на диагонали - приближённые собственные значения



3.  **Функция от матрицы**




In [ ]:
from scipy.interpolate import lagrange

Найдём $\sqrt{A}$.

Рассмотрим интерполяционный многочлен на спектре (т.е. на множестве собственных значений A).

In [ ]:
x = np.array([9, 6, 3])

y = x**(0.5)

poly = lagrange(x, y)

Коэффициенты интерполяционного многочлена

In [ ]:
poly

poly1d([-0.00927382,  0.32261065,  0.84768319])

Матрицы - та же, что и в примере ранее

In [ ]:
A = np.array( [[6, -2, 2], 
     [-2, 5, 0], 
     [2, 0, 7]])


Рассмотрим значение найденного полинома от матрицы

In [ ]:
B =-0.00927382 *(np.dot(A,A)) +  0.32261065 * A + 0.84768319 *np.identity(3)

Полученная матрица $B = \sqrt{A}$.

In [ ]:
B

array([[ 2.37529901, -0.44119726,  0.40410198],
       [-0.44119726,  2.19179566,  0.03709528],
       [ 0.40410198,  0.03709528,  2.61444528]])

Убедимся, что $B^2 = A$

In [ ]:
np.dot(B, B)

array([[ 5.99999882e+00, -1.99999938e+00,  1.99999921e+00],
       [-1.99999938e+00,  4.99999930e+00,  1.67080188e-07],
       [ 1.99999921e+00,  1.67080188e-07,  6.99999859e+00]])

In [ ]:
A

array([[ 6, -2,  2],
       [-2,  5,  0],
       [ 2,  0,  7]])

Success)