In [1]:
import numpy as np
import numpy.linalg as nla
import scipy.linalg as sla
import copy
import pandas as pd

**Метод Фадеева-Леверрье**


Строим семейство матриц $B_i$ и полиномы $p_i$ по формулам:

\begin{aligned}
B_1 = A & \qquad & p_1 = \operatorname{tr}B_1 \\
B_2 = A (B_1 - p_1 I) & \qquad & p_2 = \frac{1}{2}\operatorname{tr}B_2 \\
\dots & \qquad & \dots \\
B_{k} = A (B_{k-1} - p_{k-1} I) & \qquad & p_k = \frac{1}{k}\operatorname{tr}B_k \\
\dots & \qquad & \dots \\
B_n = A (B_{n-1} - p_{n-1} I) & \qquad & p_n = \frac{1}{n}\operatorname{tr}B_n 
\end{aligned}


In [2]:
A = [[2, -1, 2], 
     [-1, 2, 1], 
     [1, -1, 2]]

In [6]:
B1 = A
B1

[[2, -1, 2], [-1, 2, 1], [1, -1, 2]]

In [9]:
p1 = np.trace(B1)
p1

6

In [12]:
B2 = A@(B1 - p1 * np.identity(3))
B2

array([[-5.,  0., -5.],
       [ 3., -8., -4.],
       [-1.,  1., -7.]])

In [14]:
p2 = (1/2)*np.trace(B2)
p2

-10.0

In [15]:
B3 = A@(B2 - p2 * np.identity(3))
B3

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [16]:
p3 = (1/3)*np.trace(B3)
p3

5.0

Характеристический многочлен находится по формуле:

$$p(\lambda) = \lambda^n - p_1 \lambda^{n-1} - p_2 \lambda^{n-2}  - \dots -  p_n. $$


В данном случае $$p(x) = x^3 - 6 x^2 + 10 x - 5$$

Обратная матрица находится по формуле:

$$A^{-1} = \frac{1}{p_n} (B_{n-1} - p_{n-1} I).$$


In [18]:
A_inv = (1/p3) * (B2 - p2 * np.identity(3))
A_inv

array([[ 1. ,  0. , -1. ],
       [ 0.6,  0.4, -0.8],
       [-0.2,  0.2,  0.6]])

Проверяем, что это действительно обратная матрица:

In [19]:
A_inv @ A

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])